In [1]:
import os
os.getcwd()


'C:\\Users\\chait\\Downloads'

In [2]:
os.chdir("C:/Users/chait/OneDrive/Desktop/Dataset/Garbage Classification")
os.getcwd()

'C:\\Users\\chait\\OneDrive\\Desktop\\Dataset\\Garbage Classification'

# Importing Libraries

In [3]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Convolution2D
from keras.layers import MaxPooling2D
from keras.layers import Flatten

Using TensorFlow backend.


# Layers Of Convolution

In [4]:
#Intialize the model
model=Sequential()

In [5]:
# Add Convolution Layer
model.add(Convolution2D(32,(3,3),input_shape=(64,64,3),activation="relu"))

Instructions for updating:
If using Keras pass *_constraint arguments to layers.


In [6]:
#Add Pooling Layer
model.add(MaxPooling2D(pool_size = (2,2)))

In [7]:
#Add Flattening Layer
model.add(Flatten())

In [8]:
#Add Hidden Layer
model.add(Dense(init="uniform",activation="relu",output_dim=120))

C:\anaconda\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=120, kernel_initializer="uniform")`
  


In [9]:
#Add Output layer
model.add(Dense(init="uniform",activation="softmax",output_dim=5))

C:\anaconda\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="softmax", units=5, kernel_initializer="uniform")`
  


In [10]:
#Compile the model
model.compile(loss="categorical_crossentropy",optimizer="adam",metrics=["accuracy"])

# Data Preprocessing

In [11]:
from keras.preprocessing.image import ImageDataGenerator

train_datagen = ImageDataGenerator(rescale = 1./255,
                                   shear_range = 0.2,
                                   zoom_range = 0.4,
                                   horizontal_flip = True)

test_datagen = ImageDataGenerator(rescale = 1./255)

In [12]:
x_train = train_datagen.flow_from_directory('C:/Users/chait/OneDrive/Desktop/Dataset/training_set',
                                                 target_size = (64, 64),
                                                 batch_size = 32,
                                                     class_mode = 'categorical')
x_test = test_datagen.flow_from_directory('C:/Users/chait/OneDrive/Desktop/Dataset/testing_set',
                                            target_size = (64, 64),
                                            batch_size = 32,
                                            class_mode = 'categorical')

Found 1671 images belonging to 5 classes.
Found 719 images belonging to 5 classes.


In [13]:
print(x_train.class_indices)

{'cardboard': 0, 'glass': 1, 'metal': 2, 'paper': 3, 'plastic': 4}


# Model Training

In [14]:
model.fit_generator(x_train, steps_per_epoch=1500, epochs=5, validation_data=x_test)


Epoch 1/5
1500/1500 [==============================] - 274s 183ms/step - loss: 0.8773 - accuracy: 0.6595 - val_loss: 1.2543 - val_accuracy: 0.7218
Epoch 2/5
1500/1500 [==============================] - 276s 184ms/step - loss: 0.4452 - accuracy: 0.8404 - val_loss: 0.6968 - val_accuracy: 0.6940
Epoch 3/5
1500/1500 [==============================] - 276s 184ms/step - loss: 0.2663 - accuracy: 0.9077 - val_loss: 0.8485 - val_accuracy: 0.7260
Epoch 4/5
1500/1500 [==============================] - 278s 185ms/step - loss: 0.1840 - accuracy: 0.9377 - val_loss: 0.8093 - val_accuracy: 0.7191
Epoch 5/5
1500/1500 [==============================] - 278s 185ms/step - loss: 0.1291 - accuracy: 0.9573 - val_loss: 2.1696 - val_accuracy: 0.7344


# Model Building and Prediction

In [15]:
model.save("mymodel.h5")

In [16]:
from keras.models import load_model
import numpy as np
import cv2

In [17]:
model = load_model('mymodel.h5')
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])


In [18]:
from skimage.transform import resize

def detect(frame):
    try:
        img = resize(frame,(64,64))
        img = np.expand_dims(img,axis=0)
        if(np.max(img)>1):
            img = img/255.0
        prediction = model.predict(img)
        print(prediction)
        prediction = model.predict_classes(img)
        print(prediction)
    except AttributeError:
        print("shape not found")


In [30]:
frame=cv2.imread('C:/Users/chait/OneDrive/Desktop/Dataset/training_set/cardboard/cardboard100.jpg')
data = detect(frame)

[[7.0971686e-01 5.1725750e-05 3.1674907e-02 2.6299621e-04 2.5829354e-01]]
[0]


In [31]:
frame=cv2.imread('C:/Users/chait/OneDrive/Desktop/Dataset/Garbage classification/glass/glass1.jpg')
data = detect(frame)

[[1.5770875e-02 9.3005317e-01 4.9269654e-02 2.4596089e-04 4.6604150e-03]]
[1]


In [32]:
frame=cv2.imread('C:/Users/chait/OneDrive/Desktop/Dataset/testing_set/metal/metal291.jpg')
data = detect(frame)

[[1.11101065e-02 3.14475154e-04 9.80511606e-01 6.77147415e-04
  7.38670351e-03]]
[2]


In [33]:
frame=cv2.imread('C:/Users/chait/OneDrive/Desktop/Dataset/Garbage classification/paper/paper10.jpg')
data = detect(frame)

[[2.3189154e-03 2.5487954e-11 3.2385501e-09 9.9768090e-01 7.0685225e-08]]
[3]


In [23]:
frame=cv2.imread('C:/Users/chait/OneDrive/Desktop/Dataset/Garbage classification/plastic/plastic27.jpg')
data = detect(frame)

[[1.7177133e-07 2.4621154e-04 5.9152173e-04 1.2565752e-09 9.9916208e-01]]
[4]
