In [1]:
import os
os.getcwd()


'C:\\Users\\chait\\Downloads'

In [2]:
os.chdir("C:/Users/chait/OneDrive/Desktop/Dataset/Garbage Classification")
os.getcwd()

'C:\\Users\\chait\\OneDrive\\Desktop\\Dataset\\Garbage Classification'

In [16]:
from keras.models import load_model
import numpy as np
import cv2

In [17]:
model = load_model('mymodel.h5')
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])


In [18]:
from skimage.transform import resize

def detect(frame):
    try:
        img = resize(frame,(64,64))
        img = np.expand_dims(img,axis=0)
        if(np.max(img)>1):
            img = img/255.0
        prediction = model.predict(img)
        print(prediction)
        prediction = model.predict_classes(img)
        print(prediction)
    except AttributeError:
        print("shape not found")


In [30]:
frame=cv2.imread('C:/Users/chait/OneDrive/Desktop/Dataset/training_set/cardboard/cardboard100.jpg')
data = detect(frame)

[[7.0971686e-01 5.1725750e-05 3.1674907e-02 2.6299621e-04 2.5829354e-01]]
[0]


In [31]:
frame=cv2.imread('C:/Users/chait/OneDrive/Desktop/Dataset/Garbage classification/glass/glass1.jpg')
data = detect(frame)

[[1.5770875e-02 9.3005317e-01 4.9269654e-02 2.4596089e-04 4.6604150e-03]]
[1]


In [32]:
frame=cv2.imread('C:/Users/chait/OneDrive/Desktop/Dataset/testing_set/metal/metal291.jpg')
data = detect(frame)

[[1.11101065e-02 3.14475154e-04 9.80511606e-01 6.77147415e-04
  7.38670351e-03]]
[2]


In [33]:
frame=cv2.imread('C:/Users/chait/OneDrive/Desktop/Dataset/Garbage classification/paper/paper10.jpg')
data = detect(frame)

[[2.3189154e-03 2.5487954e-11 3.2385501e-09 9.9768090e-01 7.0685225e-08]]
[3]


In [23]:
frame=cv2.imread('C:/Users/chait/OneDrive/Desktop/Dataset/Garbage classification/plastic/plastic27.jpg')
data = detect(frame)

[[1.7177133e-07 2.4621154e-04 5.9152173e-04 1.2565752e-09 9.9916208e-01]]
[4]
